const FracPumpsData = [
  {id: 0, name: 'Well ABC', Pad: 'Devon XYZ', Customer: 'Devon', Fleet: 'Fleet 5', DateStarted: '2018/01/01', DateEnded: '2018/01/01', Stages: '50', PumpingHours: '105:34', NPTHours: '105:34', status: 'Finsihed'},
  {id: 1, name: 'Well ABC', Pad: 'Devon XYZ', Customer: 'Devon', Fleet: 'Fleet 5', DateStarted: '2018/01/01', DateEnded: '2018/01/01', Stages: '50', PumpingHours: '105:34', NPTHours: '105:34', status: 'Finsihed'},
  // {id: 0, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 1, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 2, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 3, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 4, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 5, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 6, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 7, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 8, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 9, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 11, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 12, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 13, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 14, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 15, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 16, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 17, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 18, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 19, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 20, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 21, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 22, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 23, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 24, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 25, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 26, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 27, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 28, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 29, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 30, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 31, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-310659', currentHours: '1313', location: 'Fleet'},
  // {id: 32, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-230659', currentHours: '1233', location: 'Fleet'},
  // {id: 33, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-203359', currentHours: '123', location: 'Fleet'},
  // {id: 34, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20634,', currentHours: '123', location: 'Fleet'},
  // {id: 35, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20635', currentHours: '123', location: 'Fleet'},
  // {id: 36, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20636', currentHours: '123', location: 'Fleet'},
  // {id: 37, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 38, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 39, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 40, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 41, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 42, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 43, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 44, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 45, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 46, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 47, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 48, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 49, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 50, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 51, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 52, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 53, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 54, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},
  // {id: 55, engine: 'CAT', Fluidend: 'Kerr', fluidendSize:'Q', FESerialNumber: '19-20659', currentHours: '123', location: 'Fleet'},


]

export default FracPumpsData
