const usersData = [
  {id: 0, name: 'Jed Hinjosa', email: 'jedfracing.com', role: 'District Manager', Fleet: 'NA', Crew: 'NA'},
  {id: 1, name: 'Jethro Hays', email: 'jethrofracing.com', role: 'Frac Manager', Fleet: 'NA', Crew: 'NA'},
  {id: 2, name: 'Jesse Benavides', email: 'jessefracing.com', role: 'Frac Manager', Fleet: 'NA', Crew: 'NA'},
  {id: 3, name: 'Arnulfo Caballer', email: 'arnulfofracing.com', role: 'Frac Manager', Fleet: 'NA', Crew: 'NA'},
  {id: 4, name: 'Andy Snider', email: 'andyfracing.com', role: 'Frac Manager', Fleet: 'NA', Crew: 'NA'},
  {id: 5, name: 'Rigo Mencha', email: 'Rigo@fracing.com', role: 'Field Supervisor', Fleet: '1', Crew: 'NA'},
  {id: 6, name: 'Herardo Canales', email: 'herardo@fracing.com', role: 'Supervisor', Fleet: '1', Crew: 'A'},
  {id: 7, name: 'Javier Vazquez', email: 'javier@fracing.com', role: 'Supervisor', Fleet: '1', Crew: 'A'},
  {id: 8, name: 'Shallie McDonald', email: 'shallie@fracing.com', role: 'Supervisor', Fleet: '1', Crew: 'B'},
  {id: 9, name: 'Gabriel Morales', email: 'gabriel@fracing.com', role: 'Supervisor', Fleet: '1', Crew: 'B'},
  {id: 10, name: 'Brandon McDonald', email: 'brandon@fracing.com', role: 'Supervisor', Fleet: '1', Crew: 'C'},
  {id: 11, name: 'Joshua Stockon', email: 'joshua@fracing.com', role: 'Supervisor', Fleet: '1', Crew: 'C'},
  {id: 12, name: 'Kaleb Phipps', email: 'kaleb@fracing.com', role: 'Field Supervisor', Fleet: '2', Crew: 'NA'},
  {id: 13, name: 'MarcoAntonio Garcia', email: 'MarcoAntonio@fracing.com', role: 'Supervisor', Fleet: '2', Crew: 'A'},
  {id: 14, name: 'Chris Simpson', email: 'chris.simpson@fracing.com', role: 'Supervisor', Fleet: '2', Crew: 'A'},
  {id: 15, name: 'Marco Montoya', email: 'Marco@fracing.com', role: 'Supervisor', Fleet: '2', Crew: 'B'},
  {id: 16, name: 'Joel Falcon', email: 'joel@fracing.com', role: 'Supervisor', Fleet: '2', Crew: 'B'},
  {id: 17, name: 'Jesse Regalado', email: 'jesse@fracing.com', role: 'Supervisor', Fleet: '2', Crew: 'C'},
  {id: 18, name: 'Donovan De Rosa', email: 'donovan.derosa@fracing.com', role: 'Supervisor', Fleet: '2', Crew: 'C'},
  {id: 19, name: 'Darryl Westbrook', email: 'darryl@fracing.com', role: 'Field Supervisor', Fleet: '3', Crew: 'NA'},
  {id: 20, name: 'Kenneth Brown', email: 'kenneth.brown@fracing.com', role: 'Supervisor', Fleet: '3', Crew: 'A'},
  {id: 21, name: 'Frank Estrada', email: 'frank.estrada@fracing.com', role: 'Supervisor', Fleet: '3', Crew: 'A'},
  {id: 22, name: 'Michael Richardson', email: 'michael.richardson@fracing.com', role: 'Supervisor', Fleet: '3', Crew: 'B'},
  {id: 23, name: 'Rustin Jackson', email: 'rustin.jackson@fracing.com', role: 'Supervisor', Fleet: '3', Crew: 'B'},
  {id: 24, name: 'Reyes Esqueda', email: 'reyes@fracing.com', role: 'Supervisor', Fleet: '3', Crew: 'C'},
  {id: 25, name: 'Charles Oliphant', email: 'charles@fracing.com', role: 'Supervisor', Fleet: '3', Crew: 'C'},
  {id: 26, name: 'Valentin Rangel', email: 'val@fracing.com', role: 'Supervisor', Fleet: '4', Crew: 'A'},
  {id: 27, name: 'Alan Jolley', email: 'alan@fracing.com', role: 'Supervisor', Fleet: '4', Crew: 'A'},
  {id: 28, name: 'Conner Hedges', email: 'conner@fracing.com', role: 'Supervisor', Fleet: '4', Crew: 'B'},
  {id: 29, name: 'Saul Lopez', email: 'saul@fracing.com', role: 'Supervisor', Fleet: '4', Crew: 'B'},
  {id: 30, name: 'Eduardo Rodriguez', email: 'Eduardo@fracing.com', role: 'Supervisor', Fleet: '4', Crew: 'C'},
  {id: 32, name: 'Rolando Flores', email: 'rolando@fracing.com', role: 'Supervisor', Fleet: '4', Crew: 'C'},
  {id: 32, name: 'Eli Zapata', email: 'eli@fracing.com', role: 'Field Supervisor', Fleet: '4', Crew: 'NA'},
  {id: 33, name: 'Faustino Garica', email: 'faustino@fracing.com', role: 'Field Supervisor', Fleet: '5', Crew: 'NA'},
  {id: 34, name: 'Jesus Barrera', email: 'jesus.barrera@@fracing.com', role: 'Supervisor', Fleet: '5', Crew: 'A'},
  {id: 35, name: 'Fabian Cano', email: 'fabian@fracing.com', role: ' Supervisor', Fleet: '5', Crew: 'A'},
  {id: 36, name: 'Vinny Ramos', email: 'vinny@fracing.com', role: 'Supervisor', Fleet: '5', Crew: 'B'},
  {id: 37, name: 'Ezequiel Arrendondo', email: 'ezequiel@fracing.com', role: 'Supervisor', Fleet: '5', Crew: 'B'},
  {id: 38, name: 'John Limas', email: 'john@fracing.com', role: 'Admin', Fleet: '5', Crew: 'C'},
  {id: 39, name: 'Rey Ramirez', email: 'rey@fracing.com', role: 'Supervisor', Fleet: '5', Crew: 'C'},
  {id: 40, name: 'Jose Davila', email: 'jose@fracing.com', role: 'Field Supervisor', Fleet: '6', Crew: 'NA'},
  {id: 41, name: 'Brandon Morgan', email: 'brandon.morgan@fracing.com', role: 'Supervisor', Fleet: '6', Crew: 'A'},
  {id: 42, name: 'Tijay Drew', email: 'tijay.drew@fracing.com', role: 'Field Supervisor', Fleet: '6', Crew: 'A'},
  {id: 43, name: 'Rudolfo De La Santos', email: 'rudy@fracing.com', role: 'Admin', Fleet: '6', Crew: 'B'},
  {id: 44, name: 'Ben Lofton', email: 'ben.lofton@fracing.com', role: 'Field Supervisor', Fleet: '6', Crew: 'B'},
  {id: 45, name: 'Adrian Macias', email: 'adrian.marcia@fracing.com', role: 'Supervisor', Fleet: '6', Crew: 'C'},
  {id: 45, name: 'Nativdad Rios', email: 'nativdad.rios@fracing.com', role: 'Supervisor', Fleet: '6', Crew: 'C'},
]

export default usersData

